<?php

namespace ContainerEdPv8AT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeaveRequestControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\LeaveRequestController' shared autowired service.
     *
     * @return \App\Controller\LeaveRequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Service\\PSGCService'] ??= new \App\Service\PSGCService());

        $container->services['App\\Controller\\LeaveRequestController'] = $instance = new \App\Controller\LeaveRequestController(($container->privates['App\\Service\\APIRequest'] ??= new \App\Service\APIRequest()), ($container->privates['App\\Service\\APIFunctions'] ?? self::getAPIFunctionsService($container)), $a, $a, ($container->privates['logger'] ?? self::getLoggerService($container)), ($container->privates['App\\Service\\ExportXLSService'] ??= new \App\Service\ExportXLSService()));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\LeaveRequestController', $container));

        return $instance;
    }
}
