<?php

namespace ContainerEdPv8AT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectManagementControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ProjectManagementController' shared autowired service.
     *
     * @return \App\Controller\ProjectManagementController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProjectManagementController'] = $instance = new \App\Controller\ProjectManagementController(($container->privates['App\\Service\\APIRequest'] ??= new \App\Service\APIRequest()), ($container->privates['App\\Service\\APIFunctions'] ?? self::getAPIFunctionsService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)), ($container->privates['cache.my_redis'] ?? $container->load('getCache_MyRedisService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ProjectManagementController', $container));

        return $instance;
    }
}
