<?php

namespace ContainerXYjwBvP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSSSConfigControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SSSConfigController' shared autowired service.
     *
     * @return \App\Controller\SSSConfigController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SSSConfigController.php';

        $container->services['App\\Controller\\SSSConfigController'] = $instance = new \App\Controller\SSSConfigController(($container->privates['App\\Service\\APIRequest'] ??= new \App\Service\APIRequest()), ($container->privates['App\\Service\\APIFunctions'] ?? self::getAPIFunctionsService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\SSSConfigController', $container));

        return $instance;
    }
}
