<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W8n4ycWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.W8n4ycW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W8n4ycW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pagibigConfigRepository' => ['privates', 'App\\Repository\\PagibigConfigRepository', 'getPagibigConfigRepositoryService', true],
        ], [
            'pagibigConfigRepository' => 'App\\Repository\\PagibigConfigRepository',
        ]);
    }
}
