<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_81ESyLaService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.81ESyLa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.81ESyLa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payrollProfileRepo' => ['privates', 'App\\Repository\\EmployeePayrollProfileRepository', 'getEmployeePayrollProfileRepositoryService', true],
        ], [
            'payrollProfileRepo' => 'App\\Repository\\EmployeePayrollProfileRepository',
        ]);
    }
}
