<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendanceTypesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AttendanceTypesRepository' shared autowired service.
     *
     * @return \App\Repository\AttendanceTypesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AttendanceTypesRepository'] = new \App\Repository\AttendanceTypesRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
