<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEcKeysetGeneratorCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Jose\Component\Console\EcKeysetGeneratorCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\EcKeysetGeneratorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\EcKeysetGeneratorCommand'] = $instance = new \Jose\Component\Console\EcKeysetGeneratorCommand();

        $instance->setName('keyset:generate:ec');
        $instance->setDescription('Generate an EC key set (JWKSet format)');

        return $instance;
    }
}
