<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeOvertimeRequestControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EmployeeOvertimeRequestController' shared autowired service.
     *
     * @return \App\Controller\EmployeeOvertimeRequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EmployeeOvertimeRequestController'] = $instance = new \App\Controller\EmployeeOvertimeRequestController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\EmployeeOvertimeRequestRepository'] ?? $container->load('getEmployeeOvertimeRequestRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\EmployeeOvertimeRequestController', $container));

        return $instance;
    }
}
