<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeaveRequestControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\LeaveRequestController' shared autowired service.
     *
     * @return \App\Controller\LeaveRequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\LeaveRequestController'] = $instance = new \App\Controller\LeaveRequestController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['App\\Service\\AuditLog'] ?? $container->load('getAuditLogService')), ($container->privates['App\\Service\\UserAccessValidation'] ?? $container->load('getUserAccessValidationService')), ($container->privates['App\\Repository\\LeaveRequestRepository'] ?? $container->load('getLeaveRequestRepositoryService')), ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\LeaveRequestController', $container));

        return $instance;
    }
}
