<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotBeforeCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Jose\Component\Checker\NotBeforeChecker' shared autowired service.
     *
     * @return \Jose\Component\Checker\NotBeforeChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Jose\\Component\\Checker\\NotBeforeChecker'] = new \Jose\Component\Checker\NotBeforeChecker(0, false, ($container->privates['jose.internal_clock'] ?? $container->load('getJose_InternalClockService')));
    }
}
