<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOctKeysetGeneratorCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.Jose\Component\Console\OctKeysetGeneratorCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\OctKeysetGeneratorCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('keyset:generate:oct', [], 'Generate a key set with octet keys (JWK format)', false, #[\Closure(name: 'Jose\\Component\\Console\\OctKeysetGeneratorCommand')] fn (): \Jose\Component\Console\OctKeysetGeneratorCommand => ($container->privates['Jose\\Component\\Console\\OctKeysetGeneratorCommand'] ?? $container->load('getOctKeysetGeneratorCommandService')));
    }
}
