<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRotateKeysetCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.Jose\Component\Console\RotateKeysetCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\RotateKeysetCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('keyset:rotate', [], 'Rotate a key set.', false, #[\Closure(name: 'Jose\\Component\\Console\\RotateKeysetCommand')] fn (): \Jose\Component\Console\RotateKeysetCommand => ($container->privates['Jose\\Component\\Console\\RotateKeysetCommand'] ?? $container->load('getRotateKeysetCommandService')));
    }
}
