<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncWorkerControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SyncWorkerController' shared autowired service.
     *
     * @return \App\Controller\SyncWorkerController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SyncWorkerController'] = $instance = new \App\Controller\SyncWorkerController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\SyncWorkerController', $container));

        return $instance;
    }
}
