<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSSSLoansHistoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SSSLoansHistoryRepository' shared autowired service.
     *
     * @return \App\Repository\SSSLoansHistoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SSSLoansHistoryRepository'] = new \App\Repository\SSSLoansHistoryRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
