<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalaryAdjustmentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SalaryAdjustmentRepository' shared autowired service.
     *
     * @return \App\Repository\SalaryAdjustmentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SalaryAdjustmentRepository'] = new \App\Repository\SalaryAdjustmentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
