<?php

namespace Container8QxZKhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\UserProvider' shared autowired service.
     *
     * @return \App\Security\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\UserProvider'] = new \App\Security\UserProvider(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
