<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O5cHcI0Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.o5cHcI0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o5cHcI0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'workerLogsRepository' => ['privates', 'App\\Repository\\WorkerLogsRepository', 'getWorkerLogsRepositoryService', true],
        ], [
            'workerLogsRepository' => 'App\\Repository\\WorkerLogsRepository',
        ]);
    }
}
