<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlgorithmManagerFactoryService extends App_KernelDevContainer
{
    /*
     * Gets the public 'Jose\Component\Core\AlgorithmManagerFactory' shared autowired service.
     *
     * @return \Jose\Component\Core\AlgorithmManagerFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Jose\\Component\\Core\\AlgorithmManagerFactory'] = $instance = new \Jose\Component\Core\AlgorithmManagerFactory();

        $instance->add('ES256', new \Jose\Component\Signature\Algorithm\ES256());
        $instance->add('ES384', new \Jose\Component\Signature\Algorithm\ES384());
        $instance->add('ES512', new \Jose\Component\Signature\Algorithm\ES512());
        $instance->add('HS256', new \Jose\Component\Signature\Algorithm\HS256());
        $instance->add('HS384', new \Jose\Component\Signature\Algorithm\HS384());
        $instance->add('HS512', new \Jose\Component\Signature\Algorithm\HS512());
        $instance->add('none', new \Jose\Component\Signature\Algorithm\None());
        $instance->add('RS256', new \Jose\Component\Signature\Algorithm\RS256());
        $instance->add('RS384', new \Jose\Component\Signature\Algorithm\RS384());
        $instance->add('RS512', new \Jose\Component\Signature\Algorithm\RS512());
        $instance->add('PS256', new \Jose\Component\Signature\Algorithm\PS256());
        $instance->add('PS384', new \Jose\Component\Signature\Algorithm\PS384());
        $instance->add('PS512', new \Jose\Component\Signature\Algorithm\PS512());
        $instance->add('EdDSA', new \Jose\Component\Signature\Algorithm\EdDSA());
        $instance->add('A128CBC-HS256', new \Jose\Component\Encryption\Algorithm\ContentEncryption\A128CBCHS256());
        $instance->add('A192CBC-HS384', new \Jose\Component\Encryption\Algorithm\ContentEncryption\A192CBCHS384());
        $instance->add('A256CBC-HS512', new \Jose\Component\Encryption\Algorithm\ContentEncryption\A256CBCHS512());
        $instance->add('A128GCM', new \Jose\Component\Encryption\Algorithm\ContentEncryption\A128GCM());
        $instance->add('A192GCM', new \Jose\Component\Encryption\Algorithm\ContentEncryption\A192GCM());
        $instance->add('A256GCM', new \Jose\Component\Encryption\Algorithm\ContentEncryption\A256GCM());
        $instance->add('dir', new \Jose\Component\Encryption\Algorithm\KeyEncryption\Dir());
        $instance->add('ECDH-ES', new \Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHES());
        $instance->add('ECDH-SS', new \Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHSS());
        $instance->add('RSA1_5', new \Jose\Component\Encryption\Algorithm\KeyEncryption\RSA15());
        $instance->add('RSA-OAEP', new \Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP());
        $instance->add('RSA-OAEP-256', new \Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP256());

        return $instance;
    }
}
