<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddKeyIntoKeysetCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\AddKeyIntoKeysetCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\AddKeyIntoKeysetCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\AddKeyIntoKeysetCommand'] = $instance = new \Jose\Component\Console\AddKeyIntoKeysetCommand();

        $instance->setName('keyset:add:key');
        $instance->setDescription('Add a key into a key set.');

        return $instance;
    }
}
