<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAffiliatedCompanyControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\AffiliatedCompanyController' shared autowired service.
     *
     * @return \App\Controller\AffiliatedCompanyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AffiliatedCompanyController'] = $instance = new \App\Controller\AffiliatedCompanyController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['App\\Service\\AuditLog'] ?? $container->load('getAuditLogService')), ($container->privates['App\\Service\\UserAccessValidation'] ?? $container->load('getUserAccessValidationService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\AffiliatedCompanyController', $container));

        return $instance;
    }
}
