<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvReaderService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Service\CsvReader' shared autowired service.
     *
     * @return \App\Service\CsvReader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\CsvReader'] = new \App\Service\CsvReader();
    }
}
