<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetThumbprintCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\GetThumbprintCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\GetThumbprintCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\GetThumbprintCommand'] = $instance = new \Jose\Component\Console\GetThumbprintCommand();

        $instance->setName('key:thumbprint');
        $instance->setDescription('Get the thumbprint of a JWK key.');

        return $instance;
    }
}
