<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetThumbprintCommand_LazyService extends App_KernelDevContainer
{
    /*
     * Gets the private '.Jose\Component\Console\GetThumbprintCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\GetThumbprintCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('key:thumbprint', [], 'Get the thumbprint of a JWK key.', false, #[\Closure(name: 'Jose\\Component\\Console\\GetThumbprintCommand')] fn (): \Jose\Component\Console\GetThumbprintCommand => ($container->privates['Jose\\Component\\Console\\GetThumbprintCommand'] ?? $container->load('getGetThumbprintCommandService')));
    }
}
