<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIssuedAtCheckerService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Checker\IssuedAtChecker' shared autowired service.
     *
     * @return \Jose\Component\Checker\IssuedAtChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Jose\\Component\\Checker\\IssuedAtChecker'] = new \Jose\Component\Checker\IssuedAtChecker(0, false, ($container->privates['jose.internal_clock'] ?? $container->load('getJose_InternalClockService')));
    }
}
