<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWEBuilderFactoryService extends App_KernelDevContainer
{
    /*
     * Gets the public 'Jose\Bundle\JoseFramework\Services\JWEBuilderFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\JWEBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Jose\\Bundle\\JoseFramework\\Services\\JWEBuilderFactory'] = new \Jose\Bundle\JoseFramework\Services\JWEBuilderFactory(($container->services['Jose\\Component\\Core\\AlgorithmManagerFactory'] ?? $container->load('getAlgorithmManagerFactoryService')), ($container->services['Jose\\Component\\Encryption\\Compression\\CompressionMethodManagerFactory'] ?? $container->load('getCompressionMethodManagerFactoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
