<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyAnalyzerCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\KeyAnalyzerCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\KeyAnalyzerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\KeyAnalyzerCommand'] = $instance = new \Jose\Component\Console\KeyAnalyzerCommand(($container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeyAnalyzerManager'] ?? $container->load('getKeyAnalyzerManagerService')));

        $instance->setName('key:analyze');
        $instance->setDescription('JWK quality analyzer.');

        return $instance;
    }
}
