<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyFileLoaderCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\KeyFileLoaderCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\KeyFileLoaderCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\KeyFileLoaderCommand'] = $instance = new \Jose\Component\Console\KeyFileLoaderCommand();

        $instance->setName('key:load:key');
        $instance->setDescription('Loads a key from a key file (JWK format)');

        return $instance;
    }
}
