<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeavePolicyRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\LeavePolicyRepository' shared autowired service.
     *
     * @return \App\Repository\LeavePolicyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LeavePolicyRepository'] = new \App\Repository\LeavePolicyRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
