<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOkpKeysetGeneratorCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\OkpKeysetGeneratorCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\OkpKeysetGeneratorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\OkpKeysetGeneratorCommand'] = $instance = new \Jose\Component\Console\OkpKeysetGeneratorCommand();

        $instance->setName('keyset:generate:okp');
        $instance->setDescription('Generate a key set with Octet Key Pairs keys (JWKSet format)');

        return $instance;
    }
}
