<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptimizeRsaKeyCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\OptimizeRsaKeyCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\OptimizeRsaKeyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\OptimizeRsaKeyCommand'] = $instance = new \Jose\Component\Console\OptimizeRsaKeyCommand();

        $instance->setName('key:optimize');
        $instance->setDescription('Optimize a RSA key by calculating additional primes (CRT).');

        return $instance;
    }
}
