<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPemConverterCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'Jose\Component\Console\PemConverterCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\PemConverterCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\PemConverterCommand'] = $instance = new \Jose\Component\Console\PemConverterCommand();

        $instance->setName('key:convert:pkcs1');
        $instance->setDescription('Converts a RSA or EC key into PKCS#1 key.');

        return $instance;
    }
}
