<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicKeysetCommand_LazyService extends App_KernelDevContainer
{
    /*
     * Gets the private '.Jose\Component\Console\PublicKeysetCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\PublicKeysetCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('keyset:convert:public', [], 'Convert private keys in a key set into public keys. Symmetric keys (shared keys) are not changed.', false, #[\Closure(name: 'Jose\\Component\\Console\\PublicKeysetCommand')] fn (): \Jose\Component\Console\PublicKeysetCommand => ($container->privates['Jose\\Component\\Console\\PublicKeysetCommand'] ?? $container->load('getPublicKeysetCommandService')));
    }
}
