<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRsaKeyGeneratorCommand_LazyService extends App_KernelDevContainer
{
    /*
     * Gets the private '.Jose\Component\Console\RsaKeyGeneratorCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\RsaKeyGeneratorCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('key:generate:rsa', [], 'Generate a RSA key (JWK format)', false, #[\Closure(name: 'Jose\\Component\\Console\\RsaKeyGeneratorCommand')] fn (): \Jose\Component\Console\RsaKeyGeneratorCommand => ($container->privates['Jose\\Component\\Console\\RsaKeyGeneratorCommand'] ?? $container->load('getRsaKeyGeneratorCommandService')));
    }
}
