<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Listener_Api_UserProviderService extends App_KernelDevContainer
{
    /*
     * Gets the private 'security.listener.api.user_provider' shared service.
     *
     * @return \Symfony\Component\Security\Http\EventListener\UserProviderListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.listener.api.user_provider'] = new \Symfony\Component\Security\Http\EventListener\UserProviderListener(($container->privates['App\\Security\\UserProvider'] ?? $container->load('getUserProviderService')));
    }
}
