<?php

namespace Container3DD6uZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectedEmployeeLeavesControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\SelectedEmployeeLeavesController' shared autowired service.
     *
     * @return \App\Controller\SelectedEmployeeLeavesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SelectedEmployeeLeavesController'] = $instance = new \App\Controller\SelectedEmployeeLeavesController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\SelectedEmployeeLeavesRepository'] ?? $container->load('getSelectedEmployeeLeavesRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\SelectedEmployeeLeavesController', $container));

        return $instance;
    }
}
