<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LeavePolicy extends \App\Entity\LeavePolicy implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'calendar_color' => [parent::class, 'calendar_color', null],
        "\0".parent::class."\0".'days' => [parent::class, 'days', null],
        "\0".parent::class."\0".'department' => [parent::class, 'department', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'increment_amount' => [parent::class, 'increment_amount', null],
        "\0".parent::class."\0".'is_carried_over' => [parent::class, 'is_carried_over', null],
        "\0".parent::class."\0".'leaveRequests' => [parent::class, 'leaveRequests', null],
        "\0".parent::class."\0".'marital' => [parent::class, 'marital', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'selectedEmployeeLeaves' => [parent::class, 'selectedEmployeeLeaves', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'year' => [parent::class, 'year', null],
        "\0".parent::class."\0".'yearlyEmployeeLeaves' => [parent::class, 'yearlyEmployeeLeaves', null],
        "\0".parent::class."\0".'years_before_increment' => [parent::class, 'years_before_increment', null],
        'calendar_color' => [parent::class, 'calendar_color', null],
        'days' => [parent::class, 'days', null],
        'department' => [parent::class, 'department', null],
        'description' => [parent::class, 'description', null],
        'gender' => [parent::class, 'gender', null],
        'id' => [parent::class, 'id', null],
        'increment_amount' => [parent::class, 'increment_amount', null],
        'is_carried_over' => [parent::class, 'is_carried_over', null],
        'leaveRequests' => [parent::class, 'leaveRequests', null],
        'marital' => [parent::class, 'marital', null],
        'name' => [parent::class, 'name', null],
        'selectedEmployeeLeaves' => [parent::class, 'selectedEmployeeLeaves', null],
        'type' => [parent::class, 'type', null],
        'year' => [parent::class, 'year', null],
        'yearlyEmployeeLeaves' => [parent::class, 'yearlyEmployeeLeaves', null],
        'years_before_increment' => [parent::class, 'years_before_increment', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
