<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MainModules extends \App\Entity\MainModules implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'administration' => [parent::class, 'administration', null],
        "\0".parent::class."\0".'emp_leaves' => [parent::class, 'emp_leaves', null],
        "\0".parent::class."\0".'humanres' => [parent::class, 'humanres', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'payroll' => [parent::class, 'payroll', null],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null],
        "\0".parent::class."\0".'submodule' => [parent::class, 'submodule', null],
        "\0".parent::class."\0".'userType' => [parent::class, 'userType', null],
        'administration' => [parent::class, 'administration', null],
        'emp_leaves' => [parent::class, 'emp_leaves', null],
        'humanres' => [parent::class, 'humanres', null],
        'id' => [parent::class, 'id', null],
        'payroll' => [parent::class, 'payroll', null],
        'project' => [parent::class, 'project', null],
        'submodule' => [parent::class, 'submodule', null],
        'userType' => [parent::class, 'userType', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
