<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'archived' => [parent::class, 'archived', null],
        "\0".parent::class."\0".'auditTrailLogs' => [parent::class, 'auditTrailLogs', null],
        "\0".parent::class."\0".'biometricData' => [parent::class, 'biometricData', null],
        "\0".parent::class."\0".'birthdate' => [parent::class, 'birthdate', null],
        "\0".parent::class."\0".'block' => [parent::class, 'block', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'contactNum' => [parent::class, 'contactNum', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'emp_shift' => [parent::class, 'emp_shift', null],
        "\0".parent::class."\0".'employeeRecords' => [parent::class, 'employeeRecords', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_assignable_proj' => [parent::class, 'is_assignable_proj', null],
        "\0".parent::class."\0".'is_straight_time' => [parent::class, 'is_straight_time', null],
        "\0".parent::class."\0".'is_worker' => [parent::class, 'is_worker', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'loginCount' => [parent::class, 'loginCount', null],
        "\0".parent::class."\0".'lot' => [parent::class, 'lot', null],
        "\0".parent::class."\0".'middleName' => [parent::class, 'middleName', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phase' => [parent::class, 'phase', null],
        "\0".parent::class."\0".'profilePhoto' => [parent::class, 'profilePhoto', null],
        "\0".parent::class."\0".'province' => [parent::class, 'province', null],
        "\0".parent::class."\0".'removed' => [parent::class, 'removed', null],
        "\0".parent::class."\0".'reset_token' => [parent::class, 'reset_token', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'street' => [parent::class, 'street', null],
        "\0".parent::class."\0".'token_expiry' => [parent::class, 'token_expiry', null],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null],
        "\0".parent::class."\0".'user_type' => [parent::class, 'user_type', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        "\0".parent::class."\0".'zip' => [parent::class, 'zip', null],
        'address' => [parent::class, 'address', null],
        'archived' => [parent::class, 'archived', null],
        'auditTrailLogs' => [parent::class, 'auditTrailLogs', null],
        'biometricData' => [parent::class, 'biometricData', null],
        'birthdate' => [parent::class, 'birthdate', null],
        'block' => [parent::class, 'block', null],
        'city' => [parent::class, 'city', null],
        'contactNum' => [parent::class, 'contactNum', null],
        'country' => [parent::class, 'country', null],
        'email' => [parent::class, 'email', null],
        'emp_shift' => [parent::class, 'emp_shift', null],
        'employeeRecords' => [parent::class, 'employeeRecords', null],
        'firstName' => [parent::class, 'firstName', null],
        'gender' => [parent::class, 'gender', null],
        'id' => [parent::class, 'id', null],
        'is_active' => [parent::class, 'is_active', null],
        'is_assignable_proj' => [parent::class, 'is_assignable_proj', null],
        'is_straight_time' => [parent::class, 'is_straight_time', null],
        'is_worker' => [parent::class, 'is_worker', null],
        'lastName' => [parent::class, 'lastName', null],
        'loginCount' => [parent::class, 'loginCount', null],
        'lot' => [parent::class, 'lot', null],
        'middleName' => [parent::class, 'middleName', null],
        'password' => [parent::class, 'password', null],
        'phase' => [parent::class, 'phase', null],
        'profilePhoto' => [parent::class, 'profilePhoto', null],
        'province' => [parent::class, 'province', null],
        'removed' => [parent::class, 'removed', null],
        'reset_token' => [parent::class, 'reset_token', null],
        'roles' => [parent::class, 'roles', null],
        'status' => [parent::class, 'status', null],
        'street' => [parent::class, 'street', null],
        'token_expiry' => [parent::class, 'token_expiry', null],
        'userId' => [parent::class, 'userId', null],
        'user_type' => [parent::class, 'user_type', null],
        'username' => [parent::class, 'username', null],
        'zip' => [parent::class, 'zip', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
