<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Department extends \App\Entity\Department implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'code' => [parent::class, 'code', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'division' => [parent::class, 'division', null],
        "\0".parent::class."\0".'employeeRecords' => [parent::class, 'employeeRecords', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isArchived' => [parent::class, 'isArchived', null],
        "\0".parent::class."\0".'leavePolicies' => [parent::class, 'leavePolicies', null],
        "\0".parent::class."\0".'manager' => [parent::class, 'manager', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'recipient_division' => [parent::class, 'recipient_division', null],
        'code' => [parent::class, 'code', null],
        'description' => [parent::class, 'description', null],
        'division' => [parent::class, 'division', null],
        'employeeRecords' => [parent::class, 'employeeRecords', null],
        'id' => [parent::class, 'id', null],
        'isArchived' => [parent::class, 'isArchived', null],
        'leavePolicies' => [parent::class, 'leavePolicies', null],
        'manager' => [parent::class, 'manager', null],
        'name' => [parent::class, 'name', null],
        'recipient_division' => [parent::class, 'recipient_division', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
