<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Worker extends \App\Entity\Worker implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'emp_record' => [parent::class, 'emp_record', null],
        "\0".parent::class."\0".'empcode' => [parent::class, 'empcode', null],
        "\0".parent::class."\0".'erContact' => [parent::class, 'erContact', null],
        "\0".parent::class."\0".'erName' => [parent::class, 'erName', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'workerDocs' => [parent::class, 'workerDocs', null],
        "\0".parent::class."\0".'workerId' => [parent::class, 'workerId', null],
        "\0".parent::class."\0".'workerLog' => [parent::class, 'workerLog', null],
        'emp_record' => [parent::class, 'emp_record', null],
        'empcode' => [parent::class, 'empcode', null],
        'erContact' => [parent::class, 'erContact', null],
        'erName' => [parent::class, 'erName', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'lastname' => [parent::class, 'lastname', null],
        'photo' => [parent::class, 'photo', null],
        'position' => [parent::class, 'position', null],
        'status' => [parent::class, 'status', null],
        'workerDocs' => [parent::class, 'workerDocs', null],
        'workerId' => [parent::class, 'workerId', null],
        'workerLog' => [parent::class, 'workerLog', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
