<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \App\Entity\Project implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archived' => [parent::class, 'archived', null],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'employeeProjects' => [parent::class, 'employeeProjects', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'project_type' => [parent::class, 'project_type', null],
        "\0".parent::class."\0".'subdivision' => [parent::class, 'subdivision', null],
        'archived' => [parent::class, 'archived', null],
        'categories' => [parent::class, 'categories', null],
        'code' => [parent::class, 'code', null],
        'description' => [parent::class, 'description', null],
        'employeeProjects' => [parent::class, 'employeeProjects', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'project_type' => [parent::class, 'project_type', null],
        'subdivision' => [parent::class, 'subdivision', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
