<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SelectedEmployeeLeaves extends \App\Entity\SelectedEmployeeLeaves implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carried_over_days' => [parent::class, 'carried_over_days', null],
        "\0".parent::class."\0".'carry_over_policy' => [parent::class, 'carry_over_policy', null],
        "\0".parent::class."\0".'employee_leave' => [parent::class, 'employee_leave', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'leaveRequests' => [parent::class, 'leaveRequests', null],
        "\0".parent::class."\0".'leave_policy' => [parent::class, 'leave_policy', null],
        "\0".parent::class."\0".'no_of_days' => [parent::class, 'no_of_days', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'used_days' => [parent::class, 'used_days', null],
        'carried_over_days' => [parent::class, 'carried_over_days', null],
        'carry_over_policy' => [parent::class, 'carry_over_policy', null],
        'employee_leave' => [parent::class, 'employee_leave', null],
        'id' => [parent::class, 'id', null],
        'leaveRequests' => [parent::class, 'leaveRequests', null],
        'leave_policy' => [parent::class, 'leave_policy', null],
        'no_of_days' => [parent::class, 'no_of_days', null],
        'status' => [parent::class, 'status', null],
        'used_days' => [parent::class, 'used_days', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
