<?php

namespace Container2SxyhvX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tlw3KNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tlw3K_N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tlw3K_N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\LeavePolicyRepository', 'getLeavePolicyRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\LeavePolicyRepository',
        ]);
    }
}
