<?php

namespace Container2SxyhvX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIssuedAtCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Jose\Component\Checker\IssuedAtChecker' shared autowired service.
     *
     * @return \Jose\Component\Checker\IssuedAtChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'Checker'.\DIRECTORY_SEPARATOR.'ClaimChecker.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'Checker'.\DIRECTORY_SEPARATOR.'HeaderChecker.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'Checker'.\DIRECTORY_SEPARATOR.'IssuedAtChecker.php';

        return $container->privates['Jose\\Component\\Checker\\IssuedAtChecker'] = new \Jose\Component\Checker\IssuedAtChecker(0, false, ($container->privates['jose.internal_clock'] ?? $container->load('getJose_InternalClockService')));
    }
}
