<?php

namespace Container2SxyhvX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWSVerifierFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Bundle\JoseFramework\Services\JWSVerifierFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\JWSVerifierFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-bundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'JWSVerifierFactory.php';

        return $container->services['Jose\\Bundle\\JoseFramework\\Services\\JWSVerifierFactory'] = new \Jose\Bundle\JoseFramework\Services\JWSVerifierFactory(($container->services['Jose\\Component\\Core\\AlgorithmManagerFactory'] ?? $container->load('getAlgorithmManagerFactoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
