<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZcu1ops\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZcu1ops/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZcu1ops.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZcu1ops\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZcu1ops\App_KernelProdContainer([
    'container.build_hash' => 'Zcu1ops',
    'container.build_id' => 'ba2115de',
    'container.build_time' => 1762823850,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZcu1ops');
