<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Blocks extends \App\Entity\Blocks implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'block_name' => [parent::class, 'block_name', null],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lots' => [parent::class, 'lots', null],
        "\0".parent::class."\0".'phase' => [parent::class, 'phase', null],
        "\0".parent::class."\0".'total_lots' => [parent::class, 'total_lots', null],
        'block_name' => [parent::class, 'block_name', null],
        'categories' => [parent::class, 'categories', null],
        'id' => [parent::class, 'id', null],
        'lots' => [parent::class, 'lots', null],
        'phase' => [parent::class, 'phase', null],
        'total_lots' => [parent::class, 'total_lots', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
