<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AuditTrailLog extends \App\Entity\AuditTrailLog implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'datetime' => [parent::class, 'datetime', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'ip_address' => [parent::class, 'ip_address', null],
        "\0".parent::class."\0".'transactions' => [parent::class, 'transactions', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'datetime' => [parent::class, 'datetime', null],
        'id' => [parent::class, 'id', null],
        'ip_address' => [parent::class, 'ip_address', null],
        'transactions' => [parent::class, 'transactions', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
