<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmployeeOvertimeRequest extends \App\Entity\EmployeeOvertimeRequest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approved_by' => [parent::class, 'approved_by', null],
        "\0".parent::class."\0".'emp_id' => [parent::class, 'emp_id', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'reason' => [parent::class, 'reason', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'time_requested' => [parent::class, 'time_requested', null],
        "\0".parent::class."\0".'worker_logs' => [parent::class, 'worker_logs', null],
        'approved_by' => [parent::class, 'approved_by', null],
        'emp_id' => [parent::class, 'emp_id', null],
        'id' => [parent::class, 'id', null],
        'reason' => [parent::class, 'reason', null],
        'status' => [parent::class, 'status', null],
        'time_requested' => [parent::class, 'time_requested', null],
        'worker_logs' => [parent::class, 'worker_logs', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
