<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmployeeProjects extends \App\Entity\EmployeeProjects implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Date' => [parent::class, 'Date', null],
        "\0".parent::class."\0".'archived' => [parent::class, 'archived', null],
        "\0".parent::class."\0".'empTasks' => [parent::class, 'empTasks', null],
        "\0".parent::class."\0".'employee' => [parent::class, 'employee', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null],
        "\0".parent::class."\0".'rendered_hours' => [parent::class, 'rendered_hours', null],
        "\0".parent::class."\0".'task' => [parent::class, 'task', null],
        'Date' => [parent::class, 'Date', null],
        'archived' => [parent::class, 'archived', null],
        'empTasks' => [parent::class, 'empTasks', null],
        'employee' => [parent::class, 'employee', null],
        'id' => [parent::class, 'id', null],
        'is_assigned' => [parent::class, 'is_assigned', null],
        'project' => [parent::class, 'project', null],
        'rendered_hours' => [parent::class, 'rendered_hours', null],
        'task' => [parent::class, 'task', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
