<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoanHistory extends \App\Entity\LoanHistory implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cash_advance' => [parent::class, 'cash_advance', null],
        "\0".parent::class."\0".'cash_advance_deduction' => [parent::class, 'cash_advance_deduction', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'employee_record' => [parent::class, 'employee_record', null],
        "\0".parent::class."\0".'hdmf_loan' => [parent::class, 'hdmf_loan', null],
        "\0".parent::class."\0".'hdmf_loan_deduction' => [parent::class, 'hdmf_loan_deduction', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'other_loans' => [parent::class, 'other_loans', null],
        "\0".parent::class."\0".'other_loans_deduction' => [parent::class, 'other_loans_deduction', null],
        "\0".parent::class."\0".'sss_loan' => [parent::class, 'sss_loan', null],
        "\0".parent::class."\0".'sss_loan_deduction' => [parent::class, 'sss_loan_deduction', null],
        'cash_advance' => [parent::class, 'cash_advance', null],
        'cash_advance_deduction' => [parent::class, 'cash_advance_deduction', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'employee_record' => [parent::class, 'employee_record', null],
        'hdmf_loan' => [parent::class, 'hdmf_loan', null],
        'hdmf_loan_deduction' => [parent::class, 'hdmf_loan_deduction', null],
        'id' => [parent::class, 'id', null],
        'other_loans' => [parent::class, 'other_loans', null],
        'other_loans_deduction' => [parent::class, 'other_loans_deduction', null],
        'sss_loan' => [parent::class, 'sss_loan', null],
        'sss_loan_deduction' => [parent::class, 'sss_loan_deduction', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
