<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PagibigConfig extends \App\Entity\PagibigConfig implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'employeePayrollProfiles' => [parent::class, 'employeePayrollProfiles', null],
        "\0".parent::class."\0".'employee_share' => [parent::class, 'employee_share', null],
        "\0".parent::class."\0".'employer_share' => [parent::class, 'employer_share', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'monthly_compensation_cap' => [parent::class, 'monthly_compensation_cap', null],
        'employeePayrollProfiles' => [parent::class, 'employeePayrollProfiles', null],
        'employee_share' => [parent::class, 'employee_share', null],
        'employer_share' => [parent::class, 'employer_share', null],
        'id' => [parent::class, 'id', null],
        'monthly_compensation_cap' => [parent::class, 'monthly_compensation_cap', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
