<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LeaveRequest extends \App\Entity\LeaveRequest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'date_end' => [parent::class, 'date_end', null],
        "\0".parent::class."\0".'date_start' => [parent::class, 'date_start', null],
        "\0".parent::class."\0".'document' => [parent::class, 'document', null],
        "\0".parent::class."\0".'emp_record' => [parent::class, 'emp_record', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_half_day' => [parent::class, 'is_half_day', null],
        "\0".parent::class."\0".'leave_policies' => [parent::class, 'leave_policies', null],
        "\0".parent::class."\0".'reason' => [parent::class, 'reason', null],
        "\0".parent::class."\0".'selected_leave' => [parent::class, 'selected_leave', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'total_days_requested' => [parent::class, 'total_days_requested', null],
        "\0".parent::class."\0".'updated_by' => [parent::class, 'updated_by', null],
        "\0".parent::class."\0".'year' => [parent::class, 'year', null],
        'created_at' => [parent::class, 'created_at', null],
        'date_end' => [parent::class, 'date_end', null],
        'date_start' => [parent::class, 'date_start', null],
        'document' => [parent::class, 'document', null],
        'emp_record' => [parent::class, 'emp_record', null],
        'id' => [parent::class, 'id', null],
        'is_half_day' => [parent::class, 'is_half_day', null],
        'leave_policies' => [parent::class, 'leave_policies', null],
        'reason' => [parent::class, 'reason', null],
        'selected_leave' => [parent::class, 'selected_leave', null],
        'status' => [parent::class, 'status', null],
        'total_days_requested' => [parent::class, 'total_days_requested', null],
        'updated_by' => [parent::class, 'updated_by', null],
        'year' => [parent::class, 'year', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
