<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DTRAdjutments extends \App\Entity\DTRAdjutments implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adjusted_date' => [parent::class, 'adjusted_date', null],
        "\0".parent::class."\0".'emp_record' => [parent::class, 'emp_record', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'worker_logs' => [parent::class, 'worker_logs', null],
        'adjusted_date' => [parent::class, 'adjusted_date', null],
        'emp_record' => [parent::class, 'emp_record', null],
        'id' => [parent::class, 'id', null],
        'worker_logs' => [parent::class, 'worker_logs', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
