<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \App\Entity\Category implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archived' => [parent::class, 'archived', null],
        "\0".parent::class."\0".'block' => [parent::class, 'block', null],
        "\0".parent::class."\0".'blocks' => [parent::class, 'blocks', null],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isOverhead' => [parent::class, 'isOverhead', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'lot' => [parent::class, 'lot', null],
        "\0".parent::class."\0".'lots' => [parent::class, 'lots', null],
        "\0".parent::class."\0".'model' => [parent::class, 'model', null],
        "\0".parent::class."\0".'owner' => [parent::class, 'owner', null],
        "\0".parent::class."\0".'phase' => [parent::class, 'phase', null],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null],
        'archived' => [parent::class, 'archived', null],
        'block' => [parent::class, 'block', null],
        'blocks' => [parent::class, 'blocks', null],
        'code' => [parent::class, 'code', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'isOverhead' => [parent::class, 'isOverhead', null],
        'location' => [parent::class, 'location', null],
        'lot' => [parent::class, 'lot', null],
        'lots' => [parent::class, 'lots', null],
        'model' => [parent::class, 'model', null],
        'owner' => [parent::class, 'owner', null],
        'phase' => [parent::class, 'phase', null],
        'project' => [parent::class, 'project', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
