<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PayrollGroups extends \App\Entity\PayrollGroups implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_end' => [parent::class, 'date_end', null],
        "\0".parent::class."\0".'date_start' => [parent::class, 'date_start', null],
        "\0".parent::class."\0".'employeePayrolls' => [parent::class, 'employeePayrolls', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'remarks' => [parent::class, 'remarks', null],
        'date_end' => [parent::class, 'date_end', null],
        'date_start' => [parent::class, 'date_start', null],
        'employeePayrolls' => [parent::class, 'employeePayrolls', null],
        'id' => [parent::class, 'id', null],
        'remarks' => [parent::class, 'remarks', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
