<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notifications extends \App\Entity\Notifications implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'action' => [parent::class, 'action', null],
        "\0".parent::class."\0".'datetime' => [parent::class, 'datetime', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'notification_type' => [parent::class, 'notification_type', null],
        "\0".parent::class."\0".'recipient_department' => [parent::class, 'recipient_department', null],
        "\0".parent::class."\0".'recipient_division' => [parent::class, 'recipient_division', null],
        "\0".parent::class."\0".'recipient_employee_record' => [parent::class, 'recipient_employee_record', null],
        "\0".parent::class."\0".'sender_employee_record' => [parent::class, 'sender_employee_record', null],
        'action' => [parent::class, 'action', null],
        'datetime' => [parent::class, 'datetime', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'notification_type' => [parent::class, 'notification_type', null],
        'recipient_department' => [parent::class, 'recipient_department', null],
        'recipient_division' => [parent::class, 'recipient_division', null],
        'recipient_employee_record' => [parent::class, 'recipient_employee_record', null],
        'sender_employee_record' => [parent::class, 'sender_employee_record', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
