<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PagibigLoansHistory extends \App\Entity\PagibigLoansHistory implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'current_amount' => [parent::class, 'current_amount', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'deduction' => [parent::class, 'deduction', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'pagibig_loans_history' => [parent::class, 'pagibig_loans_history', null],
        "\0".parent::class."\0".'payroll_profile' => [parent::class, 'payroll_profile', null],
        "\0".parent::class."\0".'previous_amount' => [parent::class, 'previous_amount', null],
        "\0".parent::class."\0".'remark' => [parent::class, 'remark', null],
        'current_amount' => [parent::class, 'current_amount', null],
        'date' => [parent::class, 'date', null],
        'deduction' => [parent::class, 'deduction', null],
        'id' => [parent::class, 'id', null],
        'pagibig_loans_history' => [parent::class, 'pagibig_loans_history', null],
        'payroll_profile' => [parent::class, 'payroll_profile', null],
        'previous_amount' => [parent::class, 'previous_amount', null],
        'remark' => [parent::class, 'remark', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
