<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmployeeAttachments extends \App\Entity\EmployeeAttachments implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'attachment_name' => [parent::class, 'attachment_name', null],
        "\0".parent::class."\0".'attachment_size' => [parent::class, 'attachment_size', null],
        "\0".parent::class."\0".'date_uploaded' => [parent::class, 'date_uploaded', null],
        "\0".parent::class."\0".'employee' => [parent::class, 'employee', null],
        "\0".parent::class."\0".'file' => [parent::class, 'file', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'original_file_name' => [parent::class, 'original_file_name', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'attachment_name' => [parent::class, 'attachment_name', null],
        'attachment_size' => [parent::class, 'attachment_size', null],
        'date_uploaded' => [parent::class, 'date_uploaded', null],
        'employee' => [parent::class, 'employee', null],
        'file' => [parent::class, 'file', null],
        'id' => [parent::class, 'id', null],
        'original_file_name' => [parent::class, 'original_file_name', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
