<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxConfig extends \App\Entity\TaxConfig implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'employeePayrollProfiles' => [parent::class, 'employeePayrollProfiles', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'tax_bracket_name' => [parent::class, 'tax_bracket_name', null],
        "\0".parent::class."\0".'tax_bracket_range' => [parent::class, 'tax_bracket_range', null],
        "\0".parent::class."\0".'tax_bracket_range_end' => [parent::class, 'tax_bracket_range_end', null],
        "\0".parent::class."\0".'tax_deduction_amount' => [parent::class, 'tax_deduction_amount', null],
        "\0".parent::class."\0".'tax_deduction_percent' => [parent::class, 'tax_deduction_percent', null],
        'employeePayrollProfiles' => [parent::class, 'employeePayrollProfiles', null],
        'id' => [parent::class, 'id', null],
        'tax_bracket_name' => [parent::class, 'tax_bracket_name', null],
        'tax_bracket_range' => [parent::class, 'tax_bracket_range', null],
        'tax_bracket_range_end' => [parent::class, 'tax_bracket_range_end', null],
        'tax_deduction_amount' => [parent::class, 'tax_deduction_amount', null],
        'tax_deduction_percent' => [parent::class, 'tax_deduction_percent', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
