<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxShield extends \App\Entity\TaxShield implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Remarks' => [parent::class, 'Remarks', null],
        "\0".parent::class."\0".'daily_tax_shield' => [parent::class, 'daily_tax_shield', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'monthly_tax_shield' => [parent::class, 'monthly_tax_shield', null],
        "\0".parent::class."\0".'payroll' => [parent::class, 'payroll', null],
        'Remarks' => [parent::class, 'Remarks', null],
        'daily_tax_shield' => [parent::class, 'daily_tax_shield', null],
        'id' => [parent::class, 'id', null],
        'monthly_tax_shield' => [parent::class, 'monthly_tax_shield', null],
        'payroll' => [parent::class, 'payroll', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
