<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ThirteenthMonthPayConfig extends \App\Entity\ThirteenthMonthPayConfig implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'employee_payroll_profile' => [parent::class, 'employee_payroll_profile', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'include_salary' => [parent::class, 'include_salary', null],
        "\0".parent::class."\0".'include_salary_adjustment' => [parent::class, 'include_salary_adjustment', null],
        "\0".parent::class."\0".'include_tax_shield_pay' => [parent::class, 'include_tax_shield_pay', null],
        'employee_payroll_profile' => [parent::class, 'employee_payroll_profile', null],
        'id' => [parent::class, 'id', null],
        'include_salary' => [parent::class, 'include_salary', null],
        'include_salary_adjustment' => [parent::class, 'include_salary_adjustment', null],
        'include_tax_shield_pay' => [parent::class, 'include_tax_shield_pay', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
