<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR6hUxe3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR6hUxe3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR6hUxe3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR6hUxe3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR6hUxe3\App_KernelDevDebugContainer([
    'container.build_hash' => 'R6hUxe3',
    'container.build_id' => '10a91b6a',
    'container.build_time' => 1762911840,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR6hUxe3');
