<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYjwBvP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYjwBvP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXYjwBvP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXYjwBvP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXYjwBvP\App_KernelDevDebugContainer([
    'container.build_hash' => 'XYjwBvP',
    'container.build_id' => '8ea948cd',
    'container.build_time' => 1762320301,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYjwBvP');
