<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdPv8AT\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdPv8AT/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerEdPv8AT.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerEdPv8AT\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerEdPv8AT\App_KernelDevContainer([
    'container.build_hash' => 'EdPv8AT',
    'container.build_id' => '2c60ae42',
    'container.build_time' => 1762823859,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdPv8AT');
