<?php

namespace ContainerZcu1ops;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSSSConfigControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SSSConfigController' shared autowired service.
     *
     * @return \App\Controller\SSSConfigController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SSSConfigController'] = $instance = new \App\Controller\SSSConfigController(($container->privates['App\\Service\\APIRequest'] ??= new \App\Service\APIRequest()), ($container->privates['App\\Service\\APIFunctions'] ?? self::getAPIFunctionsService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\SSSConfigController', $container));

        return $instance;
    }
}
