<?php

namespace ContainerTetgxhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeePayrollProfileControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EmployeePayrollProfileController' shared autowired service.
     *
     * @return \App\Controller\EmployeePayrollProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Service\\PSGCService'] ??= new \App\Service\PSGCService());

        $container->services['App\\Controller\\EmployeePayrollProfileController'] = $instance = new \App\Controller\EmployeePayrollProfileController(($container->privates['App\\Service\\APIRequest'] ??= new \App\Service\APIRequest()), ($container->privates['App\\Service\\APIFunctions'] ?? self::getAPIFunctionsService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)), $a, $a);

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\EmployeePayrollProfileController', $container));

        return $instance;
    }
}
