<?php

namespace ContainerTetgxhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\UX\TwigComponent\ComponentTemplateFinder(($container->privates['twig.loader.native_filesystem'] ?? self::getTwig_Loader_NativeFilesystemService($container)), NULL), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'breadcrumb' => [false, 'App\\Components\\Breadcrumb', 'getBreadcrumbService', true],
        ], [
            'breadcrumb' => '?',
        ]), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), $a, ['breadcrumb' => ['key' => 'breadcrumb', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'service_id' => 'App\\Components\\Breadcrumb', 'class' => 'App\\Components\\Breadcrumb', 'template' => 'components/breadcrumb.html.twig']], ['App\\Components\\Breadcrumb' => 'breadcrumb']);
    }
}
