<?php

namespace ContainerBc7L7Cj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeProfileControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmployeeProfileController' shared autowired service.
     *
     * @return \App\Controller\EmployeeProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EmployeeProfileController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/APIRequest.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PSGCService.php';

        $a = ($container->privates['App\\Service\\PSGCService'] ??= new \App\Service\PSGCService());

        $container->services['App\\Controller\\EmployeeProfileController'] = $instance = new \App\Controller\EmployeeProfileController(($container->privates['App\\Service\\APIRequest'] ??= new \App\Service\APIRequest()), ($container->privates['logger'] ?? self::getLoggerService($container)), $a, $a);

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\EmployeeProfileController', $container));

        return $instance;
    }
}
