<?php

namespace ContainerBc7L7Cj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployee201ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Employee201Controller' shared autowired service.
     *
     * @return \App\Controller\Employee201Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Employee201Controller.php';

        $container->services['App\\Controller\\Employee201Controller'] = $instance = new \App\Controller\Employee201Controller();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Employee201Controller', $container));

        return $instance;
    }
}
