<?php

namespace ContainerXXl6F3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckerCollectorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Jose\Bundle\JoseFramework\DataCollector\CheckerCollector' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\DataCollector\CheckerCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-bundle'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Collector.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-bundle'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'CheckerCollector.php';

        $a = ($container->services['Jose\\Bundle\\JoseFramework\\Services\\ClaimCheckerManagerFactory'] ?? $container->load('getClaimCheckerManagerFactoryService'));

        if (isset($container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\CheckerCollector'])) {
            return $container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\CheckerCollector'];
        }
        $b = ($container->services['Jose\\Bundle\\JoseFramework\\Services\\HeaderCheckerManagerFactory'] ?? $container->load('getHeaderCheckerManagerFactoryService'));

        if (isset($container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\CheckerCollector'])) {
            return $container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\CheckerCollector'];
        }

        return $container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\CheckerCollector'] = new \Jose\Bundle\JoseFramework\DataCollector\CheckerCollector($a, $b);
    }
}
