<?php

namespace ContainerXXl6F3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvReaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\CsvReader' shared autowired service.
     *
     * @return \App\Service\CsvReader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CsvReader.php';

        return $container->services['App\\Service\\CsvReader'] = new \App\Service\CsvReader();
    }
}
