<?php

namespace ContainerXXl6F3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeaderCheckerManagerFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Bundle\JoseFramework\Services\HeaderCheckerManagerFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\HeaderCheckerManagerFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-bundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'HeaderCheckerManagerFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'Checker'.\DIRECTORY_SEPARATOR.'TokenTypeSupport.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'Signature'.\DIRECTORY_SEPARATOR.'JWSTokenSupport.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'Encryption'.\DIRECTORY_SEPARATOR.'JWETokenSupport.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Jose\\Bundle\\JoseFramework\\Services\\HeaderCheckerManagerFactory'])) {
            return $container->services['Jose\\Bundle\\JoseFramework\\Services\\HeaderCheckerManagerFactory'];
        }

        $container->services['Jose\\Bundle\\JoseFramework\\Services\\HeaderCheckerManagerFactory'] = $instance = new \Jose\Bundle\JoseFramework\Services\HeaderCheckerManagerFactory($a);

        $instance->add('exp', ($container->privates['Jose\\Component\\Checker\\ExpirationTimeChecker'] ?? $container->load('getExpirationTimeCheckerService')));
        $instance->add('iat', ($container->privates['Jose\\Component\\Checker\\IssuedAtChecker'] ?? $container->load('getIssuedAtCheckerService')));
        $instance->add('nbf', ($container->privates['Jose\\Component\\Checker\\NotBeforeChecker'] ?? $container->load('getNotBeforeCheckerService')));
        $instance->addTokenTypeSupport(new \Jose\Component\Signature\JWSTokenSupport());
        $instance->addTokenTypeSupport(new \Jose\Component\Encryption\JWETokenSupport());

        return $instance;
    }
}
