<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3EnSpyM\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3EnSpyM/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container3EnSpyM.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container3EnSpyM\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \Container3EnSpyM\App_KernelProdDebugContainer([
    'container.build_hash' => '3EnSpyM',
    'container.build_id' => '88028394',
    'container.build_time' => 1762823286,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3EnSpyM');
