<?php

namespace ContainerJTnQRdu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VlioE0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._VlioE0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._VlioE0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empPayrollProfile' => ['privates', 'App\\Repository\\EmployeePayrollProfileRepository', 'getEmployeePayrollProfileRepositoryService', true],
            'employeeRecordsRepository' => ['privates', 'App\\Repository\\EmployeeRecordsRepository', 'getEmployeeRecordsRepositoryService', true],
        ], [
            'empPayrollProfile' => 'App\\Repository\\EmployeePayrollProfileRepository',
            'employeeRecordsRepository' => 'App\\Repository\\EmployeeRecordsRepository',
        ]);
    }
}
