<?php

namespace ContainerJTnQRdu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IKWv1kuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IKWv1ku' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IKWv1ku'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\EmployeeAdditionalRecordsRepository', 'getEmployeeAdditionalRecordsRepositoryService', true],
        ], [
            'entityManager' => '?',
            'repository' => 'App\\Repository\\EmployeeAdditionalRecordsRepository',
        ]);
    }
}
