<?php

namespace ContainerJTnQRdu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ln5MlyQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ln5MlyQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ln5MlyQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeRepo' => ['privates', 'App\\Repository\\EmployeeRecordsRepository', 'getEmployeeRecordsRepositoryService', true],
            'empproject' => ['privates', 'App\\Repository\\EmployeeProjectsRepository', 'getEmployeeProjectsRepositoryService', true],
            'emptask' => ['privates', 'App\\Repository\\EmpTaskRepository', 'getEmpTaskRepositoryService', true],
            'projectRepo' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'employeeRepo' => 'App\\Repository\\EmployeeRecordsRepository',
            'empproject' => 'App\\Repository\\EmployeeProjectsRepository',
            'emptask' => 'App\\Repository\\EmpTaskRepository',
            'projectRepo' => 'App\\Repository\\ProjectRepository',
            'serializer' => '?',
        ]);
    }
}
