<?php

namespace ContainerJTnQRdu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V_M_YveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V.M.Yve' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V.M.Yve'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payrollRepository' => ['privates', 'App\\Repository\\EmployeePayrollRepository', 'getEmployeePayrollRepositoryService', true],
        ], [
            'payrollRepository' => 'App\\Repository\\EmployeePayrollRepository',
        ]);
    }
}
