<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditLogService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\AuditLog' shared autowired service.
     *
     * @return \App\Service\AuditLog
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\AuditLog'] = new \App\Service\AuditLog(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
