<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountabilityRecordsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AccountabilityRecordsController' shared autowired service.
     *
     * @return \App\Controller\AccountabilityRecordsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AccountabilityRecordsController'] = $instance = new \App\Controller\AccountabilityRecordsController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\AccountabilityRecordsRepository'] ?? $container->load('getAccountabilityRecordsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\AccountabilityRecordsController', $container));

        return $instance;
    }
}
