<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClaimCheckerManagerFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Jose\Bundle\JoseFramework\Services\ClaimCheckerManagerFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\ClaimCheckerManagerFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Jose\\Bundle\\JoseFramework\\Services\\ClaimCheckerManagerFactory'] = $instance = new \Jose\Bundle\JoseFramework\Services\ClaimCheckerManagerFactory(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->add('exp', ($container->privates['Jose\\Component\\Checker\\ExpirationTimeChecker'] ?? $container->load('getExpirationTimeCheckerService')));
        $instance->add('iat', ($container->privates['Jose\\Component\\Checker\\IssuedAtChecker'] ?? $container->load('getIssuedAtCheckerService')));
        $instance->add('nbf', ($container->privates['Jose\\Component\\Checker\\NotBeforeChecker'] ?? $container->load('getNotBeforeCheckerService')));

        return $instance;
    }
}
