<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWKFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Jose\Component\KeyManagement\JWKFactory' shared autowired service.
     *
     * @return \Jose\Component\KeyManagement\JWKFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Jose\\Component\\KeyManagement\\JWKFactory'] = new \Jose\Component\KeyManagement\JWKFactory();
    }
}
