<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWELoaderFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Jose\Bundle\JoseFramework\Services\JWELoaderFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\JWELoaderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Jose\\Bundle\\JoseFramework\\Services\\JWELoaderFactory'] = new \Jose\Bundle\JoseFramework\Services\JWELoaderFactory(($container->services['Jose\\Component\\Encryption\\Serializer\\JWESerializerManagerFactory'] ?? self::getJWESerializerManagerFactoryService($container)), ($container->services['Jose\\Bundle\\JoseFramework\\Services\\JWEDecrypterFactory'] ?? $container->load('getJWEDecrypterFactoryService')), ($container->services['Jose\\Bundle\\JoseFramework\\Services\\HeaderCheckerManagerFactory'] ?? $container->load('getHeaderCheckerManagerFactoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
