<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyFileLoaderCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.Jose\Component\Console\KeyFileLoaderCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\KeyFileLoaderCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('key:load:key', [], 'Loads a key from a key file (JWK format)', false, #[\Closure(name: 'Jose\\Component\\Console\\KeyFileLoaderCommand')] fn (): \Jose\Component\Console\KeyFileLoaderCommand => ($container->privates['Jose\\Component\\Console\\KeyFileLoaderCommand'] ?? $container->load('getKeyFileLoaderCommandService')));
    }
}
