<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyEnvVarProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Jose\Bundle\JoseFramework\EnvVarProcessor\KeyEnvVarProcessor' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\EnvVarProcessor\KeyEnvVarProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Jose\\Bundle\\JoseFramework\\EnvVarProcessor\\KeyEnvVarProcessor'] = new \Jose\Bundle\JoseFramework\EnvVarProcessor\KeyEnvVarProcessor();
    }
}
