<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeysetAnalyzerCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Jose\Component\Console\KeysetAnalyzerCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\KeysetAnalyzerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\KeysetAnalyzerCommand'] = $instance = new \Jose\Component\Console\KeysetAnalyzerCommand(($container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeysetAnalyzerManager'] ?? $container->load('getKeysetAnalyzerManagerService')), ($container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeyAnalyzerManager'] ?? $container->load('getKeyAnalyzerManagerService')));

        $instance->setName('keyset:analyze');
        $instance->setDescription('JWKSet quality analyzer.');

        return $instance;
    }
}
