<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\NotificationService' shared autowired service.
     *
     * @return \App\Service\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\NotificationService'] = new \App\Service\NotificationService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), new \Symfony\Component\Mailer\Mailer(($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService')), NULL, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container))));
    }
}
