<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\NotificationsController' shared autowired service.
     *
     * @return \App\Controller\NotificationsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\NotificationsController'] = $instance = new \App\Controller\NotificationsController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\NotificationsController', $container));

        return $instance;
    }
}
