<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOctKeyGeneratorCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Jose\Component\Console\OctKeyGeneratorCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\OctKeyGeneratorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\OctKeyGeneratorCommand'] = $instance = new \Jose\Component\Console\OctKeyGeneratorCommand();

        $instance->setName('key:generate:oct');
        $instance->setDescription('Generate an octet key (JWK format)');

        return $instance;
    }
}
