<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOctKeyGeneratorCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.Jose\Component\Console\OctKeyGeneratorCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\OctKeyGeneratorCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('key:generate:oct', [], 'Generate an octet key (JWK format)', false, #[\Closure(name: 'Jose\\Component\\Console\\OctKeyGeneratorCommand')] fn (): \Jose\Component\Console\OctKeyGeneratorCommand => ($container->privates['Jose\\Component\\Console\\OctKeyGeneratorCommand'] ?? $container->load('getOctKeyGeneratorCommandService')));
    }
}
