<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicKeyCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.Jose\Component\Console\PublicKeyCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.Jose\\Component\\Console\\PublicKeyCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('key:convert:public', [], 'Convert a private key into public key. Symmetric keys (shared keys) are not changed.', false, #[\Closure(name: 'Jose\\Component\\Console\\PublicKeyCommand')] fn (): \Jose\Component\Console\PublicKeyCommand => ($container->privates['Jose\\Component\\Console\\PublicKeyCommand'] ?? $container->load('getPublicKeyCommandService')));
    }
}
