<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRsaKeysetGeneratorCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Jose\Component\Console\RsaKeysetGeneratorCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\RsaKeysetGeneratorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Jose\\Component\\Console\\RsaKeysetGeneratorCommand'] = $instance = new \Jose\Component\Console\RsaKeysetGeneratorCommand();

        $instance->setName('keyset:generate:rsa');
        $instance->setDescription('Generate a key set with RSA keys (JWK format)');

        return $instance;
    }
}
