<?php

namespace ContainerHMhrj69;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserTypeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UserTypeRepository' shared autowired service.
     *
     * @return \App\Repository\UserTypeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UserTypeRepository'] = new \App\Repository\UserTypeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
