<?php

namespace Container3EnSpyM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A5_1PH4Service extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.A5.1PH4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A5.1PH4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taxConfigRepository' => ['privates', 'App\\Repository\\TaxConfigRepository', 'getTaxConfigRepositoryService', true],
        ], [
            'taxConfigRepository' => 'App\\Repository\\TaxConfigRepository',
        ]);
    }
}
