<?php

namespace Container3EnSpyM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vfi5cVEService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.vfi5cVE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vfi5cVE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeRecordsRepo' => ['privates', 'App\\Repository\\EmployeeRecordsRepository', 'getEmployeeRecordsRepositoryService', true],
            'pagibigRepo' => ['privates', 'App\\Repository\\PagibigConfigRepository', 'getPagibigConfigRepositoryService', true],
            'philhealthRepo' => ['privates', 'App\\Repository\\PhilHealthConfigRepository', 'getPhilHealthConfigRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\EmployeePayrollProfileRepository', 'getEmployeePayrollProfileRepositoryService', true],
            'sssRepo' => ['privates', 'App\\Repository\\SSSConfigRepository', 'getSSSConfigRepositoryService', true],
            'taxRepo' => ['privates', 'App\\Repository\\TaxConfigRepository', 'getTaxConfigRepositoryService', true],
        ], [
            'employeeRecordsRepo' => 'App\\Repository\\EmployeeRecordsRepository',
            'pagibigRepo' => 'App\\Repository\\PagibigConfigRepository',
            'philhealthRepo' => 'App\\Repository\\PhilHealthConfigRepository',
            'repository' => 'App\\Repository\\EmployeePayrollProfileRepository',
            'sssRepo' => 'App\\Repository\\SSSConfigRepository',
            'taxRepo' => 'App\\Repository\\TaxConfigRepository',
        ]);
    }
}
