<?php

namespace Container3EnSpyM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeLeavesControllerService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmployeeLeavesController' shared autowired service.
     *
     * @return \App\Controller\EmployeeLeavesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'EmployeeLeavesController.php';

        $container->services['App\\Controller\\EmployeeLeavesController'] = $instance = new \App\Controller\EmployeeLeavesController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['App\\Service\\AuditLog'] ?? $container->load('getAuditLogService')), ($container->privates['App\\Service\\UserAccessValidation'] ?? $container->load('getUserAccessValidationService')), ($container->privates['App\\Repository\\LeaveRequestRepository'] ?? $container->load('getLeaveRequestRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\EmployeeLeavesController', $container));

        return $instance;
    }
}
