<?php

namespace Container3EnSpyM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeysetAnalyzerManagerService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'Jose\Component\KeyManagement\Analyzer\KeysetAnalyzerManager' shared autowired service.
     *
     * @return \Jose\Component\KeyManagement\Analyzer\KeysetAnalyzerManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'KeyManagement'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'KeysetAnalyzerManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'KeyManagement'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'KeysetAnalyzer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'KeyManagement'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'MixedKeyTypes.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-library'.\DIRECTORY_SEPARATOR.'KeyManagement'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'MixedPublicAndPrivateKeys.php';

        $container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeysetAnalyzerManager'] = $instance = new \Jose\Component\KeyManagement\Analyzer\KeysetAnalyzerManager();

        $instance->add(new \Jose\Component\KeyManagement\Analyzer\MixedKeyTypes());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\MixedPublicAndPrivateKeys());

        return $instance;
    }
}
