<?php

namespace Container3EnSpyM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptimizeRsaKeyCommand_LazyService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.Jose\Component\Console\OptimizeRsaKeyCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.Jose\\Component\\Console\\OptimizeRsaKeyCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('key:optimize', [], 'Optimize a RSA key by calculating additional primes (CRT).', false, #[\Closure(name: 'Jose\\Component\\Console\\OptimizeRsaKeyCommand')] fn (): \Jose\Component\Console\OptimizeRsaKeyCommand => ($container->privates['Jose\\Component\\Console\\OptimizeRsaKeyCommand'] ?? $container->load('getOptimizeRsaKeyCommandService')));
    }
}
